name: Deploy to Digital Ocean droplet
on:
    pull_request:
        types: [closed]

jobs:
    deploy:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to droplet using SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PRIVATE_KEY }}
                  debug: true
                  script: |
                      cd fs5-gestiondesocios-frontend/
                      git pull https://github.com/fullstacktf/fs5-gestiondesocios-frontend.git
                      docker stop dockerize-vuejs-app-1
                      docker rm dockerize-vuejs-app-1
                      docker rmi vue
                      docker build -t vue .
                      docker run -d -p 80:80 --rm --name dockerize-vuejs-app-1 vue